# Generated by Django 4.2.4 on 2024-06-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
