# Generated by Django 4.2.4 on 2024-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_activity_type_delete_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return')], max_length=10),
        ),
    ]
