# Generated by Django 4.2.4 on 2024-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
