# Generated by Django 4.2.4 on 2024-06-29 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_review_email_remove_review_name_review_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0009_remove_activity_is_returned_activity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
