# Generated by Django 4.2.4 on 2024-06-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_alter_activity_book_alter_activity_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
    ]
