# Generated by Django 4.2.4 on 2024-06-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_remove_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='balance_after_activity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
